apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1USXhOVEF3TWpReU1sb1hEVE0wTVRJeE5UQXdNalF5TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVp2CmcydHoyUzl0NWFhQ2cyK1BIZTRaamlXZW52aGVXTTM0Y3NEOTdYalpmN3V1dSsrL2xmbmlDcmRuU0doVTFUZzYKNGpUU01Wd1p2MlBpZlhScEFKT3Y4OWNHek1mQ284YXEyTVVjdjRBSnN4UW4rdGtsZFRzZS9BVnE5Y2E4aUNMUApvUWQ4UU9YYllQRzNBSURSV3JnN005cHI5VkhsVVdBS3VnWlNMZ0JLRm43S2V1WWdJdlpRd29ISlJZU203NjVwCjFuNWtxNjZDYWQvVDAyL1VvTnB0RjNQUWVtMWxOWW5DU2tKNkVOZXZRek8yU3htekpqRnJMRytrQmdYdlUvekgKZmkwRG1tNnVVVmQvN1JvOW15c01VcUJ3UG5DREMyZ0tJSXA3Vnk5anl0OGpxR0NPcGpyTVBBb2pPSDFtdGZYdApLUDRoR1BwR0VJS2Y3MlNTaXIwQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCbnJlVTBJcXlSWXNYbzhLVG11K1NvRTE4NDlNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBdEtZRjAwTlZUekE3TlJkWThNbkpLQWNQa09iQUpUaWkzVW5qSWpKWHQ3M0I2ZFBXUwp1S0ZjbnFLc0s2Ti9pMTZBSXh5OUlMcXlyRmtMbkpMdjQ2ZmZtdWI4YjJLaG16dUV1cnM2Rnl2Kzc3R1JyaXFqCmNpVmVGcll6TFd4TEQ5VDIxUk9ITGpkTW84ZDh4UllMMzBMaXc0UndXSTYwV250eHI5NjNIMmc5bnFsbEJHNTUKTm5MU2M4OGRCbVNPdy9VM1cxWEFtYjZOMjVXQStrQ284K1BrdHRKOFp1NWFFbjZpelJSa1l5bXY0SUlubTBJSwp6TXZyYjk3eHpNTHBRVTJVY0E5UDF5aDk1Q3pUbXBRK3RoSk14M0dLdlJoOTRXUXRFZ3FXU2l6clYrWTAxTnFwCmEyS2JRYk5zdlNwcjdmQTA4R2N0ZE5PNmY4YlhveWZWY0kregotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://935cf650-6d05-467b-8d3f-9e75aa5f9e43.api.k8s.fr-par.scw.cloud:6443
  name: scaleway-cluster
contexts:
- context:
    cluster: scaleway-cluster
    user: scaleway-user
  name: scaleway-context
current-context: scaleway-context
kind: Config
preferences: {}
users:
- name: scaleway-user
  user:
    token: 8FDDNvwqzs9VMeyo8fbJqOqOo83ha19SrTl4PcGpklyPlCCiJwiOpMNQ
